### ISSUE TITLE
iso bigger than 4gb

### ISSUE THREAD

**Issue by kabutor** [alkisg/liveusb#5]
What you do if a iso image, like a Ubuntu one is bigger than 4Gb, any way to do ext4 partitions so grub can load from there and fit the isos in that partition?

**Comment by alkisg** [comment]
Hi kabutor, sure you can add a second ext4, ntfs, exfat etc partition with gparted, to use for bigger .isos or even .raw disk images.
But you'll also need to manually add a `set root=(xxx)` command in grub.cfg, so that liveusb searches for .isos in the second partition instead of the first one.
Unfortunately I don't have time/plans to automate or optimize grub.cfg too much, it's mostly there for people that are already familiar with the grub scripting language and can customize grub.cfg themselves.
That said, patches welcome!

**Comment by kabutor** [comment]
I forked your repo and been doing some tests and now it works. I'm more interested in a secure boot EFI (mbr is no longer usable) linux iso loader, not in testing that it works with 10 different distributions.
When I'm comfortable with the script I'll submit a PR, but I think it's gonna be a different objective that what you have here.

**Comment by kabutor** [comment]
I just see that this is still open.

I did a script to create a pendrive to boot on a secure UEFI and it's working (very limited as it can only boot images with signed kernel, you can't do a multi ISO boot because it's not going to work with the vast majority of live distributions) , but although I'm using some of your code, it's very different I don't see the point of commit a PR.
I think it's best to close this. :)
